### ISSUE TITLE
use in react native

### ISSUE THREAD

**Issue by mohsen158** [pirumpi/sftp-upload#10]
hi 
how can i use thi in react native??
i get this error
bundling failed: "Unable to resolve module `fs` from `D:\\react-native\\taav\\node_modules\\sftp-upload\\lib\\sftp-upload.js`:

**Comment by SpencerTorres** [comment]
`fs` is a NodeJS library. It can't be packaged to run in browsers. 

Using this on the client side is insecure for the remote server's credentials anyway. What I recommend is accepting uploads on the client side with something like `react-dropzone` and uploading it to a node server. From there you can use this module to forward the uploads to other remote servers.

**Comment by pirumpi** [comment]
@SpencerTorres thanks for your comment, I think your suggested approach is adequate for what @mohsen158 is trying to accomplish.
