### ISSUE TITLE
Copy Single file

### ISSUE THREAD

**Issue by prabhash1785** [pirumpi/sftp-upload#2]
Can this module be used to copy one file instead of the whole directory? I tried to copy one file to remote server but I got error saying source is not a directory.

**Comment by pirumpi** [comment]
That is a good question. Right now it does not work that way but I could add a file parameter that takes an array with specific files within a folder. Would that solution work for you?

**Comment by prabhash1785** [comment]
Yeah that would work. Thanks!

**Comment by pirumpi** [comment]
I'll be pushing a commit soon to address this issue

**Comment by nguyenchr** [comment]
+1 on this enhancement

**Comment by BenjaminN** [comment]
+1 on this too ! thanks

**Comment by William-Olson** [comment]
+1
