### ISSUE TITLE
Uploading to home directory not root

### ISSUE THREAD

**Issue by grimurd** [pirumpi/sftp-upload#6]
I'm trying to upload to a folder on my server.

The options object looks like this:

```
    var options = {
            host: 'server.local',
            username: 'user',
            path: './folder',
            remoteDir: '/var/db/www/server.local/htdocs/',
            privateKey: fs.readFileSync('./ssh')
        },
```

However when i upload it goes into my users folder instead of the root folder. So the path looks like this:

/home/user/var/db/www/server.local/htdocs

I've checked and the user has the write permission to the remote folder.

Is there something i'm doing wrong?

**Comment by bhanuc** [comment]
I directly used the scp2 module and its working great as of now .

**Comment by toni89** [comment]
`SftpUpload.prototype.uploadFiles = function(files, opt){
    var fns = [],
        client = new Client(opt),
        totalFiles = files.length,
        pendingFiles = 0,
        self = this;
    
    client.on('connect', function(){
        self.emit('connect');
    });
    
    files.forEach(function(file){
        fns.push(
            function(cb){
                var localFile = path.relative(opt.path, file),
                    remoteFile = path.join(opt.remoteDir, localFile);

                client.upload(file, '.'+remoteFile, function(err){
                    pendingFiles += 1;
                    self.emit('uploading', {
                        file: file,
                        percent: Math.round((pendingFiles*100)/totalFiles)
                    });
                    cb(err);
                });
            }
        );
    });`

It's in this line. Please remove the dot in front of remoteFile.
`client.upload(file, '.'+remoteFile, function(err){`

**Comment by r-polonskiy** [comment]
Please, update your package on NPMJS! It still has that bug!

**Comment by broerse** [comment]
Please run `npm publish` or give me npm publish rights.

**Comment by pirumpi** [comment]
npm is now updated
