### ISSUE TITLE
show debug logs

### ISSUE THREAD

**Issue by fr-kshibata** [pirumpi/sftp-upload#7]
its possible in ssh2 to show debug logs. how to do I do it in sftp-upload?

**Comment by pirumpi** [comment]
What kind of logs are you trying to see? Right now you can add logs to the following events like this:

.on('uploading', function(pgs){
        console.log('Uploading', pgs.file);
        console.log(pgs.percent+'% completed');
    })
 .on('error', function(err){
        console.log(err);
    })
    .on('completed', function(){
        console.log('Upload Completed');
    })

**Comment by fr-kshibata** [comment]
I see i meant more explicit logs
```
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: pktLen:572,padLen:8,remainLen:568
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: KEXDH_REPLY
[CLIENT] DEBUG: Checking host key format
[CLIENT] DEBUG: Checking signature format
[CLIENT] DEBUG: Verifying host fingerprint
[CLIENT] DEBUG: Host accepted by default (no verification)
[CLIENT] DEBUG: Verifying signature
[CLIENT] DEBUG: Outgoing: Writing NEWKEYS
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 8)
[CLIENT] DEBUG: Parser: IN_PACKET
[CLIENT] DEBUG: Parser: pktLen:12,padLen:10,remainLen:8
[CLIENT] DEBUG: Parser: IN_PACKETDATA
[CLIENT] DEBUG: Parser: IN_PACKETDATAAFTER, packet: NEWKEYS
[CLIENT] DEBUG: Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
[CLIENT] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
```

**Comment by fr-kshibata** [comment]
Never mind I got it 
I used @mscdex ssh2 debug 

debug: console

Since ssh2->scp2->sftp-upload
